# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MSMapsModules' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for MSMapsModules
  pod 'MicrosoftMapsSDK', '~> 1.1.4' 

  target 'MSMapsModulesTests' do
    # Pods for testing
    project './MSMapsModules.xcodeproj'
    pod 'MicrosoftMapsSDK', '~> 1.1.4'
  end

end
