# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MSMapsModulesReferenceApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for MSMapsModulesReferenceApp
  pod 'MicrosoftMapsSDK', '~> 1.1.4'
  pod 'MSMapsModules', :git => 'https://github.com/microsoft/BingMapsNativeModules.git', :commit => '150bc44e2176d0536dc6430615f3227f8a60f39a'

end
