# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MSMapsModulesReferenceApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for MSMapsModulesReferenceApp
  pod 'MicrosoftMapsSDK', '~> 1.1.4'
  pod 'MSMapsModules', :git => 'https://github.com/microsoft/BingMapsNativeModules.git', :commit => '10c2c12c8fbd48041a768ad5036ae414ab4ac965'

end
