# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MSMapsModulesReferenceApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MSMapsModulesReferenceApp
  pod 'MicrosoftMapsSDK', '~> 1.1.4'
  # Modify the following line to import the library from GitHub
  # See https://guides.cocoapods.org/using/the-podfile.html for more information
  pod 'MSMapsModules', :podspec => '~/Desktop/internProject/BingMapsNativeModules'

end
